# Generated by Django 6.0.2 on 2026-03-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('hourly_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.TimeField()),
                ('daily_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('workdays_per_week', models.IntegerField()),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, max_digits=3)),
                ('paid_leave_multiplier', models.DecimalField(decimal_places=2, max_digits=3)),
                ('holiday_work_multiplier', models.DecimalField(decimal_places=2, max_digits=3)),
                ('monthly_paid_leave', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_company_admin', models.BooleanField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
