# Generated by Django 6.0.2 on 2026-03-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workprofile',
            table='work_profile',
        ),
    ]
