# Generated by Django 6.0.2 on 2026-03-15 22:36

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country_code', models.CharField(max_length=2)),
                ('logo', models.FileField(upload_to=companies.models.logo_upload_path)),
            ],
            options={
                'db_table': 'company',
                'constraints': [models.UniqueConstraint(fields=('name', 'country_code'), name='company_name_country_unique')],
            },
        ),
    ]
